version: 2.1

jobs:
    test:
        docker:
            - image: cimg/node:14.2.0
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - node-deps-v1-{{ .Branch }}-{{checksum "package.json"}}
            - run:
                  name: install packages
                  command: npm i
            - save_cache:
                  key: node-deps-v1-{{ .Branch }}-{{checksum "package.json"}}
                  paths:
                      - ~/.npm
            - run:
                  name: Run Tests
                  command: npm run test
    build-job:
        docker:
            - image: cimg/node:14.2.0
        steps:
            - run:
                  name: build job
                  command: npm run build

    deployment-job:
        docker:
            - image: cimg/node:14.2.0
        steps:
            - run:
                  name: Deploy Master to Firebase
                  command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
    test_my_app:
        jobs:
            - test
    deploy:
        jobs:
            - build-job
            - deployment-job:
                  requires:
                      - build-job
                  filters:
                      branches:
                          only: master
