version: 2.1

jobs:
    test:
        docker:
            - image: cimg/node:14.2.0
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - node-deps-v1-{{ .Branch }}-{{checksum "package.json"}}
            - run:
                  name: install packages
                  command: npm i
            - save_cache:
                  key: node-deps-v1-{{ .Branch }}-{{checksum "package.json"}}
                  paths:
                      - ~/.npm
            - run:
                  name: Run Tests
                  command: npm run test
    build_deploy:
        docker:
            - image: cimg/node:14.2.0
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - node-deps-v1-{{ .Branch }}-{{checksum "package.json"}}
            - run:
                  name: install packages
                  command: npm i
            - save_cache:
                  key: node-deps-v1-{{ .Branch }}-{{checksum "package.json"}}
                  paths:
                      - ~/.npm
            - run:
                  name: build job
                  command: npm run build
            - run:
                  name: Deploy Master to Firebase
                  command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
    test_build:
        jobs:
            - test
            - build_deploy:
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - master
